# -*- coding: utf-8 -*-
"""MC_A3_2021303.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uNDkgokIhuQdsOGe0LzLBtoWGAMc52iu
"""

import matplotlib.pyplot as plt
import numpy as np

fil = "angle_data.txt"
with open(fil, 'r') as file:
    lines = file.readlines()

time = []
x_axis = []
y_axis = []
z_axis = []

for line in lines:
    parts = line.strip().split(',')
    time.append(parts[0])
    x_axis.append(float(parts[1]))
    y_axis.append(float(parts[2]))
    z_axis.append(float(parts[3]))

def predict_future_data(original_data, num_points):
    mean = np.mean(original_data[-num_points:])
    std = np.std(original_data[-num_points:])
    return np.random.normal(mean, std, num_points)

plt.figure(figsize=(10, 6))

plt.subplot(3, 1, 1)
plt.plot(x_axis, label='Original X-axis Data')
plt.ylabel('X-axis')
plt.legend()

plt.subplot(3, 1, 2)
plt.plot(y_axis, label='Original Y-axis Data')
plt.ylabel('Y-axis')
plt.legend()

plt.subplot(3, 1, 3)
plt.plot(z_axis, label='Original Z-axis Data')
plt.ylabel('Z-axis')
plt.legend()


num_points_to_use = 50

x_axis_prediction = predict_future_data(x_axis, num_points_to_use)
y_axis_prediction = predict_future_data(y_axis, num_points_to_use)
z_axis_prediction = predict_future_data(z_axis, num_points_to_use)

x_axis_combined = np.concatenate([x_axis[:-100], x_axis_prediction])
y_axis_combined = np.concatenate([y_axis[:-100], y_axis_prediction])
z_axis_combined = np.concatenate([z_axis[:-100], z_axis_prediction])

plt.subplot(3, 1, 1)
plt.plot(x_axis_combined, label='Combined X-axis Data')
plt.legend()

plt.subplot(3, 1, 2)
plt.plot(y_axis_combined, label='Combined Y-axis Data')
plt.legend()

plt.subplot(3, 1, 3)
plt.plot(z_axis_combined, label='Combined Z-axis Data')
plt.legend()

plt.tight_layout()
plt.show()